Use bcgov-nr/action-diff-triggers

diff --git a/.github/workflows/.deploy.yml b/.github/workflows/.deploy.yml
--- a/.github/workflows/.deploy.yml
+++ b/.github/workflows/.deploy.yml
@@ -73,10 +73,43 @@ jobs:
           oc_version: 4.13
           overwrite: true
           parameters: -p ZONE=${{ inputs.target }} -p TAG=${{ inputs.tag }} ${{ inputs.parameters }}
-          post_rollout: |
-            oc create job ${{ env.JOB_JOB }} --from=cronjob/${{ env.CRONJOB }} &&
-            (oc wait --for=jsonpath='{.status.failed}'=4 job/${{ env.JOB_JOB }} --timeout=1m || true )&&
-            oc logs -l job-name=${{ env.JOB_JOB }} --tail=50 --follow &&
-            oc get job ${{ env.JOB_JOB }} &&
-            if [ $(oc get job ${{ env.JOB_JOB }} -o jsonpath='{.status.ready}') -ne 0 ]; then exit 1; fi
+          post_rollout: oc create job ${{ env.JOB_JOB }} --from=cronjob/${{ env.CRONJOB }}
           triggers: ${{ inputs.triggers }}
+
+  verify:
+    name: Verify
+    if: inputs.verify == true
+    environment: ${{ inputs.environment }}
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    steps:
+      # Send triggers to diff action
+      - id: diff
+        uses: bcgov-nr/action-diff-triggers@v0.2.0
+        with:
+          triggers: ${{ inputs.triggers }}
+          diff_branch: ${{ inputs.diff_branch }}
+
+      - name: Verify
+        if: steps.diff.outputs.triggered == true
+        run: |
+          # Check job logs
+
+          # Login
+          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
+          oc project ${{ secrets.oc_namespace }} #Safeguard!
+
+          # Follow
+          oc wait --for=jsonpath='{.status.failed}'=4 job/${{ env.JOB_JOB }} --timeout=1m || true
+          oc logs -l job-name=${{ env.JOB_JOB }} --tail=50 --follow
+
+          # Results and exit code
+          oc get job ${{ env.JOB_JOB }}
+
+          if [ $(oc get job ${{ env.JOB_JOB }} -o jsonpath='{.status.ready}') -eq 0 ]; then
+            echo "Job successful!"
+            exit 0
+          else
+            echo "Job failed!"
+            exit 1
+          fi
