Troubleshoot

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -12,48 +12,48 @@ env:
   JOB: ${{ github.event.repository.name }}-${{ github.event.number }}-sync
 
 jobs:
-  # https://github.com/bcgov-nr/action-builder-ghcr
-  builds:
-    name: Builds
-    runs-on: ubuntu-22.04
-    outputs:
-      digest: ${{ steps.builds.outputs.digest }}
-    permissions:
-      packages: write
-    timeout-minutes: 10
-    steps:
-      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
-        id: builds
-        with:
-          keep_versions: 50
-          package: sync
-          tag: ${{ github.event.number }}
-          tag_fallback: latest
-          triggers: ('sync/')
+  # # https://github.com/bcgov-nr/action-builder-ghcr
+  # builds:
+  #   name: Builds
+  #   runs-on: ubuntu-22.04
+  #   outputs:
+  #     digest: ${{ steps.builds.outputs.digest }}
+  #   permissions:
+  #     packages: write
+  #   timeout-minutes: 10
+  #   steps:
+  #     - uses: bcgov-nr/action-builder-ghcr@v2.0.2
+  #       id: builds
+  #       with:
+  #         keep_versions: 50
+  #         package: sync
+  #         tag: ${{ github.event.number }}
+  #         tag_fallback: latest
+  #         triggers: ('sync/')
 
-  deploys:
-    name: Deploys
-    needs: [builds]
-    if: needs.builds.outputs.digest != ''
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploys
-        uses: bcgov-nr/action-deployer-openshift@v2.2.0
-        with:
-          file: sync/openshift.etl.yml
-          oc_namespace: ${{ secrets.OC_NAMESPACE }}
-          oc_server: ${{ vars.OC_SERVER }}
-          oc_token: ${{ secrets.OC_TOKEN }}
-          oc_version: 4.13
-          overwrite: true
-          parameters: -p ZONE=${{ github.event.number }} -p TAG=${{ github.event.number }}
-          post_rollout: 
-            oc create job ${{ env.JOB }}-${{ github.run_number }} --from=cronjob/${{ env.JOB }} &&
-            oc get job ${{ env.JOB }}-${{ github.run_number }}
+  # deploys:
+  #   name: Deploys
+  #   needs: [builds]
+  #   if: needs.builds.outputs.digest != ''
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Deploys
+  #       uses: bcgov-nr/action-deployer-openshift@v2.2.0
+  #       with:
+  #         file: sync/openshift.etl.yml
+  #         oc_namespace: ${{ secrets.OC_NAMESPACE }}
+  #         oc_server: ${{ vars.OC_SERVER }}
+  #         oc_token: ${{ secrets.OC_TOKEN }}
+  #         oc_version: 4.13
+  #         overwrite: true
+  #         parameters: -p ZONE=${{ github.event.number }} -p TAG=${{ github.event.number }}
+  #         post_rollout: 
+  #           oc create job ${{ env.JOB }}-${{ github.run_number }} --from=cronjob/${{ env.JOB }} &&
+  #           oc get job ${{ env.JOB }}-${{ github.run_number }}
 
   logs:
     name: Logs
-    needs: [deploys]
+    # needs: [deploys]
     runs-on: ubuntu-latest
     steps:
       - name: Logs
@@ -71,13 +71,15 @@ jobs:
           # Results and exit code
           oc get job ${{ env.JOB }}-${{ github.run_number }}
 
-          if [ $(oc get job ${{ env.JOB }}-${{ github.run_number }} -o jsonpath='{.status.ready}') -eq 0 ]; then
-            echo "Job failed!"
-            exit 1
-          else
-            echo "Job successful!"
-            exit 0
-          fi
+          READY=$(oc get job nr-spar-data-29-sync-130 -o jsonpath='{.status.ready}')
+          echo "READY: $READY"
+          # if [ $(oc get job ${{ env.JOB }}-${{ github.run_number }} -o jsonpath='{.status.ready}') -eq 0 ]; then
+          #   echo "Job failed!"
+          #   exit 1
+          # else
+          #   echo "Job successful!"
+          #   exit 0
+          # fi
 
   results:
     name: PR Results
