Builds

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -9,34 +9,51 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  python:
-    name: Python
-    env:
-      PIP_DISABLE_PIP_VERSION_CHECK: 1
-      PYTHONUNBUFFERED: 1
-      PYTHONDONTWRITEBYTECODE: 1
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-          cache: 'pip'
-      - working-directory: app
-        run: pip install -r ./requirements.txt
-      - working-directory: app/src/
-        run: python main.py || echo "App failing!"
+  # python:
+  #   name: Python
+  #   env:
+  #     PIP_DISABLE_PIP_VERSION_CHECK: 1
+  #     PYTHONUNBUFFERED: 1
+  #     PYTHONDONTWRITEBYTECODE: 1
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.10'
+  #         cache: 'pip'
+  #     - working-directory: app
+  #       run: pip install -r ./requirements.txt
+  #     - working-directory: app/src/
+  #       run: python main.py || echo "App failing!"
 
-  oc:
-    name: OpenShift
+  # oc:
+  #   name: OpenShift
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - name: Execute OC Test
+  #       run: |
+  #         oc version
+  #         oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
+  #         oc project ${{ secrets.OC_NAMESPACE }} # Safeguard!
+  #         oc whoami
+
+  # https://github.com/bcgov-nr/action-builder-ghcr
+  builds:
+    name: Builds
     runs-on: ubuntu-22.04
+    permissions:
+      packages: write
+    timeout-minutes: 10
     steps:
-      - name: Execute OC Test
-        run: |
-          oc version
-          oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
-          oc project ${{ secrets.OC_NAMESPACE }} # Safeguard!
-          oc whoami
+      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
+        id: builds
+        with:
+          keep_versions: 50
+          package: sync
+          tag: ${{ github.event.number }}
+          tag_fallback: latest
+          triggers: ('sync/')
 
   results:
     name: PR Results
